### ISSUE TITLE
D1 Mini Low Power Mode?

### ISSUE THREAD

**Issue by matthuisman** [wemos/D1_mini_Examples#19]
Hi,

I am wanting to have a D1 Mini use as minimal power in deep sleep as possible.
I will be using 3x AA batteries connected into the 5v line.
I have seen the schematic of the D1 Mini uses a RT9013 reg which can handle 2.2 -> 5.5V so works fine.

Is there a way to disable the D1 Mini "extras" to save power when in sleep?
eg: the UART chip

**Comment by matthuisman** [comment]
It appears the UART chip is powered by 2x 3.3V lines.
Could I maybe cut across those to disable?

Would be great having a non-permanent way to disable...

Would be cool if the UART got it's 3.3v power from a separate reg connected to USB power.
That way, if not using USB, it won't get used.

**Comment by matthuisman** [comment]
Just spotted forums. Sorry. Closing.

**Comment by Gulaschcowboy** [comment]
"Just spotted forums. Sorry. Closing."

Sorry, which forum?

**Comment by TheAustrian** [comment]
https://forum.wemos.cc

**Comment by Gulaschcowboy** [comment]
What a quick answer. But I can't find a post related to power saving by disabling e.g. UART chip. Any hints? Thanks!

**Comment by matthuisman** [comment]
It was here:
https://forum.wemos.cc/post/1316

But seems it's gone - not sure why.

Can view google cache version here:
https://webcache.googleusercontent.com/search?q=cache:Rff18Yd5-lQJ:https://forum.wemos.cc/post/1316+&cd=1&hl=en&ct=clnk&gl=nz

**Comment by TheAustrian** [comment]
Apparently the forum crashed a few weeks ago and they had no backup, so all the old posts are gone - but people there should be able to help if you open a thread.

**Comment by Gulaschcowboy** [comment]
@matthuisman @TheAustrian Thanks a bunch!

**Comment by whitebird** [comment]
Both the forum and cache link are down.

**Comment by sej7278** [comment]
would be interested in this too - like which components to remove (LED's etc.) and how to disable uart etc.

**Comment by Chief812** [comment]
> wecache is down too! anybody have decision?

**Comment by Chief812** [comment]
Disabling UART on D1 Mini is still f...ng actual!!!
