### ISSUE TITLE
Problems with OSX Sierra Driver for Wemos

### ISSUE THREAD

**Issue by jabrena** [wemos/D1_mini_Examples#25]
Hi, 

I have just installed the driver for Wemos D1 R2, but when I connect the board with the laptop, I receive a Kernel Panic in the MAC. It is very rare but it is happen when I connect the board.
https://www.wemos.cc/downloads

How to solve it?

My laptop has OSX Sierra.

Juan Antonio

**Comment by jabrena** [comment]
I fix this problem using this blog.
https://tzapu.com/ch340-ch341-serial-adapters-macos-sierra/

Maybe the official drive should be upgraded.

Juan Antonio

**Comment by jasonw-nc** [comment]
I wanted to update this thread with a solution for Mac OSX High Sierra users, specifically 10.13.4.
If you have problems with the driver using the latest OSX High Sierra please refer to the KB Article: 

https://support.apple.com/kb/HT208019

Basically, the kernel extension needs to be approved to load and is done so in system preferences/security.
