### ISSUE TITLE
MQTT on D1Mini

### ISSUE THREAD

**Issue by lettierimarco** [wemos/D1_mini_Examples#31]
I've tried with pubsub library and adafruit and the error is always 

192.168.0.59
Connecting to MQTT... 
Exception (9):
epc1=0x4020416b epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000b depc=0x00000000

ctx: cont 
sp: 3fff1ea0 end: 3fff20b0 offset: 01a0

>>>stack>>>
3fff2040:  3fffdad0 3fff0dac 3fff0fcc 4020699d  
3fff2050:  3ffe8fc0 3fff0e9c 00000000 3fffdad0  
3fff2060:  402207c3 3fff0dac 3fff0fcc 402069b0  
3fff2070:  3fff2acc 40202ae0 3fff0fcc 402026d2  
3fff2080:  3fffdad0 00000000 3fff0e9c 40202751  
3fff2090:  3fffdad0 00000000 3fff1080 402074b8  
3fff20a0:  feefeffe feefeffe 3fff1090 40100718  
<<<stack<<<

LoadStoreAlignmentCause: Load or store to an unaligned address
Decoding 9 results
0x4020416b: Adafruit_MQTT::connect() at Adafruit_MQTT.cpp line 768

Why?

**Comment by mike2nl** [comment]
@lettierimarco @wemos 
Hi,
I know this post is old but have you tested this mqtt version test for the sht30?
You can use verey other sensor of function. It's the idea and code and it works.

LINK: https://github.com/ycardon/d1mini-sht30-mqtt
