### ISSUE TITLE
D1 MINI auto-reset problem 

### ISSUE THREAD

**Issue by marksev1** [wemos/D1_mini_Examples#5]
See here: http://forum.wemos.cc/topic/21/problem-board-doesn-t-auto-reset

I have some Wemos D1 mini boards, and they don't auto-reset. I need to press the reset button for the program to be executed after I unplug and replug the usb cable. Only after a fresh upload the code executes. For my friend which also has a few of these boards they autoreset normally, he can unplug and replug and they work. I have same drivers installed then my friend which doesn't have that issue, and we also run same version of Windows and same IDE.

I tried with Arduino IDE 1.6.5r5 and also with the latest 1.6.7 and same issue. Tried also various usb cables and no fix to the problem. 
Flashing the board works normally, problem is only running the program after unpluging and repluging usb.

So i don't really know whats the problem??

**Comment by mcauser** [comment]
Could be a manufacturing flaw. I have 4 boards. Make a gist with your code and ill try it on each of mine.
